module.exports = {
    printWidth: 180,
    tabWidth: 4,
    useTabs: true,
    semi: true,
    singleQuote: true,
    quoteProps: 'as-needed',
    jsxSingleQuote: true,
    trailingComma: 'es5',
    bracketSpacing: true,
    bracketSameLine: true,
    arrowParens: 'always',
    singleAttributePerLine: true,
    embeddedLanguageFormatting: 'auto',
    htmlWhitespaceSensitivity: 'css',
    insertPragma: false,
    proseWrap: 'preserve',
    requirePragma: false,
    vueIndentScriptAndStyle: false,
    endOfLine: 'lf',
};
