module.exports = {
	magicWebSocketKey: require('./magic-websocket-key'),
	mainDir: require('./main-dir'),
	mimeDict: require('./mime-dict'),
	toByte: require('./to-byte'),
	toDecimal: require('./to-decimal'),
	updateClientLogs: require('./update-client-logs'),
	fromDataFrame: require('./from-data-frame'),
	toDataFrame: require('./to-data-frame'),
	createAcceptKey: require('./create-accept-key'),
	creteResponseHeaders: require('./create-response-headers'),
	openingHandshake: require('./opening-handshake'),
	decodePayload: require('./decode-payload'),
	opcodeDict: require('./opcode-dict'),
	updateClientConnected: require('./update-client-connected'),
};
